version: '2'

services:

  blazegraph:
    image: lyrasis/blazegraph:2.1.4
    ports:
      - 8889:8080

    volumes:
      # Should match what is in run-example.sh
      - ./gridappsd/blazegraph/data:/data
      - ./conf/rwstore.properties:/RWStore.properties

  mysql:
    image: mysql/mysql-server:5.7
  
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_PORT: 3306
  
    volumes:
      - ./gridappsdmysql:/var/lib/mysql
      - ./dumps/gridappsd_mysql_dump.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  viz:
    image: gridappsd/viz
    ports:
      - 8080:8082

    depends_on:
      - gridappsd

  gridappsd:
    image: gridappsd/gridappsd
    ports:
      - 61614:61614

    depends_on:
      - mysql
      - blazegraph

    environment:
      - GRIDAPPSD_PROJECT=/gridappsd
      - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GRIDAPPSD_PROJECT/lib:/usr/local/lib
      - FNCS_LOG_LEVEL=DEBUG4
    #entrypoint: "java -jar /gridappsd/lib/run.bnd.jar"
    entrypoint: "tail -f /dev/null"

