version: '2'

services:

  blazegraph:
    image: lyrasis/blazegraph:2.1.4
    ports:
      - 8889:8080

    volumes:
      # Should match what is in run-example.sh
      - ./gridappsd/blazegraph/data:/data
      - ./conf/rwstore.properties:/RWStore.properties

  mysql:
    image: mysql/mysql-server:5.7
    ports:
      - 3306:3306

    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_PORT: 3306

    volumes:
      - ./gridappsdmysql:/var/lib/mysql
      - ./dumps/gridappsd_mysql_dump.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  viz:
    image: gridappsd/viz${GRIDAPPSD_TAG}
    ports:
      - 8080:8082

    depends_on:
      - gridappsd

  gridappsd:
    image: gridappsd
    ports:
      - 61613:61613
      - 61614:61614
      - 61616:61616
      - 8000:8000

    working_dir: /gridappsd
    environment:
      - PATH=/gridappsd/bin:/gridappsd/lib:/gridappsd/services/fncsgossbridge/service:$PATH
      - DEBUG=1

# uncomment the volumes section for application support
#    volumes:
#      - ~/git/gridappsd-sample-app/sample_app:/gridappsd/applications/sample_app
#      - ~/git/gridappsd-sample-app/sample_app/sample_app.config:/gridappsd/applications/sample_app.config

    depends_on:
      - mysql
      - blazegraph

