version: '2'

services:

  blazegraph:
    image: lyrasis/blazegraph:2.1.4
    ports:
      - 8889:8080

    volumes:
      # Should match what is in run-example.sh
      - ./gridappsd/blazegraph/data:/data
      - ./conf/rwstore.properties:/RWStore.properties

  mysql:
    image: mysql/mysql-server:5.7

    ports:
      - 3306:3306

    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_PORT: 3306

    volumes:
      - ./gridappsdmysql:/var/lib/mysql
      - ./dumps/gridappsd_mysql_dump.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  viz:
    image: gridappsd/viz${GRIDAPPSD_TAG}
    ports:
      - 8080:8082

    depends_on:
      - gridappsd
    entrypoint: "tail -f /dev/null"

  gridappsd:
    image: gridappsd/gridappsd${GRIDAPPSD_TAG}
    ports:
      - 61614:61614
      - 61616:61616
      - 61613:61613
    working_dir: /gridappsd
    environment:
      - PATH=/gridappsd/bin:/gridappsd/lib:/gridappsd/services/fncsgossbridge/service:$PATH
    volumes:
      - ./conf:/gridappsd/conf
      - ./applications:/gridappsd/applications
      - ./services:/gridappsd/services
#      - ./log:/tmp/gridappsd/log
    depends_on:
      - mysql
      - blazegraph

    entrypoint: "tail -f /dev/null"
      #"/gridappsd/gridappsd.run.sh"
      #"java -jar lib/run.bnd.jar"
    #"tail -f /dev/null"
      #"java -jar lib/run.bnd.jar >> /tmp/gridappsd/log/goss-gridappsd.log 2>1"
